<?php
/**
 * Copyright (c) 2024. Volodymyr Hryvinskyi.  All rights reserved.
 * @author: <mailto:volodymyr@hryvinskyi.com>
 * @github: <https://github.com/hryvinskyi>
 */

declare(strict_types=1);

/**
 * @var \Hryvinskyi\EmailLogger\Block\Adminhtml\View $block
 * @var \Magento\Framework\Escaper $escaper
 */

$emailLog = $block->getLog();
?>
<div class="page-main-actions">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="404 Not Found">
            <div class="page-actions-buttons">
                <button title="Back" type="button" class="action"
                        onclick="location.href = '<?= $block->getUrl('hryvinskyi_email_log/index/index') ?>'">
                    <span>← Back</span>
                </button>
                <button title="Delete Page" type="button" class="action"
                        onclick="location.href = '<?= $block->getUrl('hryvinskyi_email_log/index/delete', ['id' => $emailLog->getLogEntryId()]) ?>'">
                    <span>Delete Log</span>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="information">
    <strong><?= $escaper->escapeHtml(__('Sender') . ':') ?></strong>
    <?= $escaper->escapeHtml($emailLog->getEmailSender()); ?>
    <hr>
    <strong><?= $escaper->escapeHtml(__('Recipient') . ':') ?></strong>
    <?= $escaper->escapeHtml($emailLog->getEmailRecipient()); ?>
    <hr>
    <b><?= $escaper->escapeHtml(__('Cc') . ':') ?></b>
    <?= $escaper->escapeHtml($emailLog->getEmailCc() == null ? __('No ') : $emailLog->getEmailCc()) ?>
    <hr>
    <b><?= $escaper->escapeHtml(__('Bcc') . ':') ?></b>
    <?= $escaper->escapeHtml($emailLog->getEmailBcc() == null ? __('No ') : $emailLog->getEmailCc()) ?>
    <hr>

    <b><?= $escaper->escapeHtml(__('Subject') . ':') ?></b>
    <?= $escaper->escapeHtml($emailLog->getEmailSubject()); ?>
    <hr>

    <b><?= $escaper->escapeHtml(__('Status') . ':') ?></b>
    <?= $escaper->escapeHtml($emailLog->getSendingStatus()); ?>
    <hr>

    <b><?= $escaper->escapeHtml(__('Created at') . ':') ?></b>
    <?= $escaper->escapeHtml($emailLog->getTimeOfSendingMail()); ?>
</div>
<?php
if ($emailLog->getEmailContent() == null): ?>
    <div class="no-content">
        <p><?=
            /* @noEscape */
            __(
                'During the recording of this log, the \'Save content\' option was disabled.
                You can enable it by clicking on %1.',
                '<a href="' . $escaper->escapeUrl(
                    $block->getUrl('adminhtml/system_config/edit/section/emailslog')
                ) . '">' . __('link') . '</a>'
            )
            ?>
        </p>
    </div>
<?php
else: ?>
    <br>
    <iframe loading="lazy" width="100%" height="700px" border="0" src="<?= $escaper->escapeUrl(
        $block->getUrl('hryvinskyi_email_log/index/viewlog', ['id' => $emailLog->getLogEntryId()])
    ); ?>"></iframe>
<?php
endif; ?>
